# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/platform_axi_smc_3_0.xci
# IP: The module: 'platform_axi_smc_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/bd_e8f5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_0/bd_e8f5_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_2/bd_e8f5_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_3/bd_e8f5_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_4/bd_e8f5_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_5/bd_e8f5_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_6/bd_e8f5_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_7/bd_e8f5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_8/bd_e8f5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_9/bd_e8f5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_10/bd_e8f5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_11/bd_e8f5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_12/bd_e8f5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_13/bd_e8f5_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_14/bd_e8f5_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_15/bd_e8f5_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_16/bd_e8f5_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_17/bd_e8f5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_18/bd_e8f5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_19/bd_e8f5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_20/bd_e8f5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_21/bd_e8f5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_22/bd_e8f5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_23/bd_e8f5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_24/bd_e8f5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_25/bd_e8f5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_26/bd_e8f5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_2/bd_e8f5_arsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_3/bd_e8f5_rsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_4/bd_e8f5_awsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_5/bd_e8f5_wsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_6/bd_e8f5_bsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_10/bd_e8f5_s00a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_11/bd_e8f5_sarn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_12/bd_e8f5_srn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_16/bd_e8f5_s01a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_17/bd_e8f5_sawn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_18/bd_e8f5_swn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_19/bd_e8f5_sbn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_20/bd_e8f5_m00s2a_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_21/bd_e8f5_m00arn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_22/bd_e8f5_m00rn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_23/bd_e8f5_m00awn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_24/bd_e8f5_m00wn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_25/bd_e8f5_m00bn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_smc_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/platform_axi_smc_3_0.xci
# IP: The module: 'platform_axi_smc_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/bd_e8f5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_0/bd_e8f5_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_2/bd_e8f5_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_3/bd_e8f5_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_4/bd_e8f5_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_5/bd_e8f5_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_6/bd_e8f5_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_7/bd_e8f5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_8/bd_e8f5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_9/bd_e8f5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_10/bd_e8f5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_11/bd_e8f5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_12/bd_e8f5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_13/bd_e8f5_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_14/bd_e8f5_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_15/bd_e8f5_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_16/bd_e8f5_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_17/bd_e8f5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_18/bd_e8f5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_19/bd_e8f5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_20/bd_e8f5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_21/bd_e8f5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_22/bd_e8f5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_23/bd_e8f5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_24/bd_e8f5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_25/bd_e8f5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_26/bd_e8f5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_2/bd_e8f5_arsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_3/bd_e8f5_rsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_4/bd_e8f5_awsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_5/bd_e8f5_wsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_6/bd_e8f5_bsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_10/bd_e8f5_s00a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_11/bd_e8f5_sarn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_12/bd_e8f5_srn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_16/bd_e8f5_s01a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_17/bd_e8f5_sawn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_18/bd_e8f5_swn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_19/bd_e8f5_sbn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_20/bd_e8f5_m00s2a_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_21/bd_e8f5_m00arn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_22/bd_e8f5_m00rn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_23/bd_e8f5_m00awn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_24/bd_e8f5_m00wn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_25/bd_e8f5_m00bn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_smc_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
