// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsbs_spike_50.h"

extern XSbs_spike_50_Config XSbs_spike_50_ConfigTable[];

XSbs_spike_50_Config *XSbs_spike_50_LookupConfig(u16 DeviceId) {
	XSbs_spike_50_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSBS_SPIKE_50_NUM_INSTANCES; Index++) {
		if (XSbs_spike_50_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSbs_spike_50_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSbs_spike_50_Initialize(XSbs_spike_50 *InstancePtr, u16 DeviceId) {
	XSbs_spike_50_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSbs_spike_50_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSbs_spike_50_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

