// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CRTL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of debug
//        bit 31~0 - debug[31:0] (Read)
// 0x14 : Control signal of debug
//        bit 0  - debug_ap_vld (Read/COR)
//        others - reserved
// 0x18 : Data signal of layerSize
//        bit 31~0 - layerSize[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of vectorSize
//        bit 31~0 - vectorSize[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL         0x00
#define XSBS_SPIKE_50_CRTL_BUS_ADDR_GIE             0x04
#define XSBS_SPIKE_50_CRTL_BUS_ADDR_IER             0x08
#define XSBS_SPIKE_50_CRTL_BUS_ADDR_ISR             0x0c
#define XSBS_SPIKE_50_CRTL_BUS_ADDR_DEBUG_DATA      0x10
#define XSBS_SPIKE_50_CRTL_BUS_BITS_DEBUG_DATA      32
#define XSBS_SPIKE_50_CRTL_BUS_ADDR_DEBUG_CTRL      0x14
#define XSBS_SPIKE_50_CRTL_BUS_ADDR_LAYERSIZE_DATA  0x18
#define XSBS_SPIKE_50_CRTL_BUS_BITS_LAYERSIZE_DATA  32
#define XSBS_SPIKE_50_CRTL_BUS_ADDR_VECTORSIZE_DATA 0x20
#define XSBS_SPIKE_50_CRTL_BUS_BITS_VECTORSIZE_DATA 32

