# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/platform_axi_smc_1_0.xci
# IP: The module: 'platform_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/bd_2854.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_0/bd_2854_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_2/bd_2854_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_3/bd_2854_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_4/bd_2854_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_5/bd_2854_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_6/bd_2854_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_7/bd_2854_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_8/bd_2854_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_9/bd_2854_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_10/bd_2854_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_11/bd_2854_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_12/bd_2854_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_13/bd_2854_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_14/bd_2854_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_15/bd_2854_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_16/bd_2854_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_17/bd_2854_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_18/bd_2854_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_19/bd_2854_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_20/bd_2854_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_21/bd_2854_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_22/bd_2854_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_23/bd_2854_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_24/bd_2854_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_25/bd_2854_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_26/bd_2854_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_2/bd_2854_arsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_3/bd_2854_rsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_4/bd_2854_awsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_5/bd_2854_wsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_6/bd_2854_bsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_10/bd_2854_s00a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_11/bd_2854_sarn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_12/bd_2854_srn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_16/bd_2854_s01a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_17/bd_2854_sawn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_18/bd_2854_swn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_19/bd_2854_sbn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_20/bd_2854_m00s2a_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_21/bd_2854_m00arn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_22/bd_2854_m00rn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_23/bd_2854_m00awn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_24/bd_2854_m00wn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_25/bd_2854_m00bn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/platform_axi_smc_1_0.xci
# IP: The module: 'platform_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/bd_2854.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_0/bd_2854_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_2/bd_2854_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_3/bd_2854_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_4/bd_2854_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_5/bd_2854_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_6/bd_2854_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_7/bd_2854_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_8/bd_2854_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_9/bd_2854_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_10/bd_2854_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_11/bd_2854_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_12/bd_2854_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_13/bd_2854_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_14/bd_2854_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_15/bd_2854_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_16/bd_2854_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_17/bd_2854_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_18/bd_2854_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_19/bd_2854_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_20/bd_2854_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_21/bd_2854_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_22/bd_2854_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_23/bd_2854_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_24/bd_2854_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_25/bd_2854_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_26/bd_2854_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_2/bd_2854_arsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_3/bd_2854_rsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_4/bd_2854_awsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_5/bd_2854_wsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_6/bd_2854_bsw_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_10/bd_2854_s00a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_11/bd_2854_sarn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_12/bd_2854_srn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_16/bd_2854_s01a2s_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_17/bd_2854_sawn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_18/bd_2854_swn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_19/bd_2854_sbn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_20/bd_2854_m00s2a_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_21/bd_2854_m00arn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_22/bd_2854_m00rn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_23/bd_2854_m00awn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_24/bd_2854_m00wn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_25/bd_2854_m00bn_0_ooc.xdc

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
