// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsbs_spike_50.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSbs_spike_50_CfgInitialize(XSbs_spike_50 *InstancePtr, XSbs_spike_50_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSbs_spike_50_Start(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSbs_spike_50_IsDone(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSbs_spike_50_IsIdle(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSbs_spike_50_IsReady(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSbs_spike_50_EnableAutoRestart(XSbs_spike_50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSbs_spike_50_DisableAutoRestart(XSbs_spike_50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_AP_CTRL, 0);
}

u32 XSbs_spike_50_Get_debug(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_DEBUG_DATA);
    return Data;
}

u32 XSbs_spike_50_Get_debug_vld(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_DEBUG_CTRL);
    return Data & 0x1;
}

void XSbs_spike_50_Set_layerSize(XSbs_spike_50 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_LAYERSIZE_DATA, Data);
}

u32 XSbs_spike_50_Get_layerSize(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_LAYERSIZE_DATA);
    return Data;
}

void XSbs_spike_50_Set_vectorSize(XSbs_spike_50 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_VECTORSIZE_DATA, Data);
}

u32 XSbs_spike_50_Get_vectorSize(XSbs_spike_50 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_VECTORSIZE_DATA);
    return Data;
}

void XSbs_spike_50_InterruptGlobalEnable(XSbs_spike_50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_GIE, 1);
}

void XSbs_spike_50_InterruptGlobalDisable(XSbs_spike_50 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_GIE, 0);
}

void XSbs_spike_50_InterruptEnable(XSbs_spike_50 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_IER);
    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XSbs_spike_50_InterruptDisable(XSbs_spike_50 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_IER);
    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XSbs_spike_50_InterruptClear(XSbs_spike_50 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_spike_50_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XSbs_spike_50_InterruptGetEnabled(XSbs_spike_50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_IER);
}

u32 XSbs_spike_50_InterruptGetStatus(XSbs_spike_50 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSbs_spike_50_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_SPIKE_50_CRTL_BUS_ADDR_ISR);
}

