# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_0_0/platform_sbs_fixedpoint_0_0.xci
# IP: The module: 'platform_sbs_fixedpoint_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_0_0/constraints/sbs_fixedpoint_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_sbs_fixedpoint_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_0_0/platform_sbs_fixedpoint_0_0.xci
# IP: The module: 'platform_sbs_fixedpoint_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_0_0/constraints/sbs_fixedpoint_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'platform_sbs_fixedpoint_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
