# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado/2017.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z020clg400-1 ../Yarib_sbs_sbs_spike_50_1_0.zip
