# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/platform/platform.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform || ORIG_REF_NAME==platform} -quiet] -quiet

# IP: bd/platform/ip/platform_processing_system7_0_0/platform_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_processing_system7_0_0 || ORIG_REF_NAME==platform_processing_system7_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_sbs_spike_50_0_0/platform_sbs_spike_50_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_sbs_spike_50_0_0 || ORIG_REF_NAME==platform_sbs_spike_50_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_sbs_accelerator_0_0/platform_sbs_accelerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_sbs_accelerator_0_0 || ORIG_REF_NAME==platform_sbs_accelerator_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_xlconcat_0_0/platform_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_xlconcat_0_0 || ORIG_REF_NAME==platform_xlconcat_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_axi_dma_0_0 || ORIG_REF_NAME==platform_axi_dma_0_0} -quiet] -quiet

# IP: bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_axi_dma_0_1 || ORIG_REF_NAME==platform_axi_dma_0_1} -quiet] -quiet

# IP: bd/platform/ip/platform_axi_smc_0/platform_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_axi_smc_0 || ORIG_REF_NAME==platform_axi_smc_0} -quiet] -quiet

# Block Designs: bd/platform/ip/platform_axi_smc_0/bd_0/bd_d051.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_10/bd_d051_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_16/bd_d051_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_23/bd_d051_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_29/bd_d051_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_33/bd_d051_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_39/bd_d051_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_34/bd_d051_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_35/bd_d051_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_36/bd_d051_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_37/bd_d051_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_38/bd_d051_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_30/bd_d051_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_31/bd_d051_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_32/bd_d051_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_26/bd_d051_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_27/bd_d051_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_28/bd_d051_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_24/bd_d051_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_25/bd_d051_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_20/bd_d051_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_21/bd_d051_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_22/bd_d051_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_17/bd_d051_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_18/bd_d051_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_19/bd_d051_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_13/bd_d051_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_14/bd_d051_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_15/bd_d051_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_11/bd_d051_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_12/bd_d051_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_7/bd_d051_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_8/bd_d051_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_9/bd_d051_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_2/bd_d051_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_3/bd_d051_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_4/bd_d051_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_5/bd_d051_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_6/bd_d051_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_0/bd_d051_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_1/bd_d051_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_rst_ps7_0_250M_0 || ORIG_REF_NAME==platform_rst_ps7_0_250M_0} -quiet] -quiet

# IP: bd/platform/ip/platform_ps7_0_axi_periph_0/platform_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_ps7_0_axi_periph_0 || ORIG_REF_NAME==platform_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/platform/ip/platform_xbar_0/platform_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_xbar_0 || ORIG_REF_NAME==platform_xbar_0} -quiet] -quiet

# IP: bd/platform/ip/platform_auto_pc_0/platform_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platform_auto_pc_0 || ORIG_REF_NAME==platform_auto_pc_0} -quiet] -quiet

# XDC: bd/platform/ip/platform_processing_system7_0_0/platform_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==platform_processing_system7_0_0 || ORIG_REF_NAME==platform_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/platform/ip/platform_sbs_spike_50_0_0/constraints/sbs_spike_50_ooc.xdc

# XDC: bd/platform/ip/platform_sbs_accelerator_0_0/constraints/sbs_accelerator_ooc.xdc

# XDC: bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==platform_axi_dma_0_0 || ORIG_REF_NAME==platform_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==platform_axi_dma_0_0 || ORIG_REF_NAME==platform_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1_ooc.xdc

# XDC: bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==platform_axi_dma_0_1 || ORIG_REF_NAME==platform_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==platform_axi_dma_0_1 || ORIG_REF_NAME==platform_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/platform/ip/platform_axi_smc_0/ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_10/bd_d051_s00a2s_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_16/bd_d051_s01a2s_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_23/bd_d051_s02a2s_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_29/bd_d051_s03a2s_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_33/bd_d051_m00s2a_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_34/bd_d051_m00arn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_35/bd_d051_m00rn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_36/bd_d051_m00awn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_37/bd_d051_m00wn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_38/bd_d051_m00bn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_30/bd_d051_sawn_1_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_31/bd_d051_swn_1_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_32/bd_d051_sbn_1_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_24/bd_d051_sarn_1_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_25/bd_d051_srn_1_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_17/bd_d051_sawn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_18/bd_d051_swn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_19/bd_d051_sbn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_11/bd_d051_sarn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_12/bd_d051_srn_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_2/bd_d051_arsw_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_3/bd_d051_rsw_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_4/bd_d051_awsw_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_5/bd_d051_wsw_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_6/bd_d051_bsw_0_ooc.xdc

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_1/bd_d051_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_1/bd_d051_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==platform_rst_ps7_0_250M_0 || ORIG_REF_NAME==platform_rst_ps7_0_250M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==platform_rst_ps7_0_250M_0 || ORIG_REF_NAME==platform_rst_ps7_0_250M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0_ooc.xdc

# XDC: bd/platform/ip/platform_xbar_0/platform_xbar_0_ooc.xdc

# XDC: bd/platform/ip/platform_auto_pc_0/platform_auto_pc_0_ooc.xdc

# XDC: bd/platform/platform_ooc.xdc
