# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.cache/wt [current_project]
set_property parent.project_path /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths /home/yarib/work/vivado_hls [current_project]
set_property ip_output_repo /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/hdl/platform_wrapper.vhd
add_files /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/platform.bd
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_processing_system7_0_0/platform_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_sbs_spike_50_0_0/constraints/sbs_spike_50_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_sbs_accelerator_0_0/constraints/sbs_accelerator_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_10/bd_d051_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_16/bd_d051_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_23/bd_d051_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_29/bd_d051_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_33/bd_d051_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_34/bd_d051_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_35/bd_d051_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_36/bd_d051_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_37/bd_d051_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_38/bd_d051_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_30/bd_d051_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_31/bd_d051_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_32/bd_d051_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_24/bd_d051_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_25/bd_d051_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_17/bd_d051_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_18/bd_d051_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_19/bd_d051_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_11/bd_d051_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_12/bd_d051_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_2/bd_d051_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_3/bd_d051_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_4/bd_d051_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_5/bd_d051_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_6/bd_d051_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_1/bd_d051_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_1/bd_d051_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_xbar_0/platform_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/ip/platform_auto_pc_0/platform_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yarib/work/vivado/sbs_custom_float/sbs_custom_float.srcs/sources_1/bd/platform/platform_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top platform_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef platform_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file platform_wrapper_utilization_synth.rpt -pb platform_wrapper_utilization_synth.pb"
