// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSBS_ACCELERATOR_H
#define XSBS_ACCELERATOR_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsbs_accelerator_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
} XSbs_accelerator_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XSbs_accelerator;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSbs_accelerator_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSbs_accelerator_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSbs_accelerator_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSbs_accelerator_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSbs_accelerator_Initialize(XSbs_accelerator *InstancePtr, u16 DeviceId);
XSbs_accelerator_Config* XSbs_accelerator_LookupConfig(u16 DeviceId);
int XSbs_accelerator_CfgInitialize(XSbs_accelerator *InstancePtr, XSbs_accelerator_Config *ConfigPtr);
#else
int XSbs_accelerator_Initialize(XSbs_accelerator *InstancePtr, const char* InstanceName);
int XSbs_accelerator_Release(XSbs_accelerator *InstancePtr);
#endif

void XSbs_accelerator_Start(XSbs_accelerator *InstancePtr);
u32 XSbs_accelerator_IsDone(XSbs_accelerator *InstancePtr);
u32 XSbs_accelerator_IsIdle(XSbs_accelerator *InstancePtr);
u32 XSbs_accelerator_IsReady(XSbs_accelerator *InstancePtr);
void XSbs_accelerator_EnableAutoRestart(XSbs_accelerator *InstancePtr);
void XSbs_accelerator_DisableAutoRestart(XSbs_accelerator *InstancePtr);

void XSbs_accelerator_Set_layerSize(XSbs_accelerator *InstancePtr, u32 Data);
u32 XSbs_accelerator_Get_layerSize(XSbs_accelerator *InstancePtr);
void XSbs_accelerator_Set_kernelSize(XSbs_accelerator *InstancePtr, u32 Data);
u32 XSbs_accelerator_Get_kernelSize(XSbs_accelerator *InstancePtr);
void XSbs_accelerator_Set_vectorSize(XSbs_accelerator *InstancePtr, u32 Data);
u32 XSbs_accelerator_Get_vectorSize(XSbs_accelerator *InstancePtr);
void XSbs_accelerator_Set_epsilon(XSbs_accelerator *InstancePtr, u32 Data);
u32 XSbs_accelerator_Get_epsilon(XSbs_accelerator *InstancePtr);

void XSbs_accelerator_InterruptGlobalEnable(XSbs_accelerator *InstancePtr);
void XSbs_accelerator_InterruptGlobalDisable(XSbs_accelerator *InstancePtr);
void XSbs_accelerator_InterruptEnable(XSbs_accelerator *InstancePtr, u32 Mask);
void XSbs_accelerator_InterruptDisable(XSbs_accelerator *InstancePtr, u32 Mask);
void XSbs_accelerator_InterruptClear(XSbs_accelerator *InstancePtr, u32 Mask);
u32 XSbs_accelerator_InterruptGetEnabled(XSbs_accelerator *InstancePtr);
u32 XSbs_accelerator_InterruptGetStatus(XSbs_accelerator *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
