# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.cache/wt [current_project]
set_property parent.project_path /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths /home/nevarez/work/vivado/hls [current_project]
update_ip_catalog
set_property ip_output_repo /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/hdl/platform_wrapper.vhd
add_files /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/platform.bd
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_processing_system7_0_0/platform_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_spike_0_0/constraints/sbs_fixedpoint_spike_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_0_0/constraints/sbs_fixedpoint_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_0/platform_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_1/platform_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_2/platform_axi_dma_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_2/platform_axi_dma_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_2/platform_axi_dma_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_3/platform_axi_dma_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_3/platform_axi_dma_0_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_dma_0_3/platform_axi_dma_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_0_1/constraints/sbs_fixedpoint_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_sbs_fixedpoint_0_2/constraints/sbs_fixedpoint_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_1/bd_d051_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_1/bd_d051_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_2/bd_d051_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_3/bd_d051_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_4/bd_d051_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_5/bd_d051_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_6/bd_d051_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_10/bd_d051_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_11/bd_d051_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_12/bd_d051_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_16/bd_d051_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_17/bd_d051_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_18/bd_d051_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_19/bd_d051_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_20/bd_d051_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_21/bd_d051_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_22/bd_d051_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_23/bd_d051_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_24/bd_d051_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/bd_0/ip/ip_25/bd_d051_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_rst_ps7_0_250M_0/platform_rst_ps7_0_250M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_1/bd_2854_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_2/bd_2854_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_3/bd_2854_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_4/bd_2854_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_5/bd_2854_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_6/bd_2854_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_10/bd_2854_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_11/bd_2854_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_12/bd_2854_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_16/bd_2854_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_17/bd_2854_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_18/bd_2854_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_19/bd_2854_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_20/bd_2854_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_21/bd_2854_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_22/bd_2854_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_23/bd_2854_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_24/bd_2854_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/bd_0/ip/ip_25/bd_2854_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_1/bd_28a4_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_1/bd_28a4_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_2/bd_28a4_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_3/bd_28a4_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_4/bd_28a4_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_5/bd_28a4_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_6/bd_28a4_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_10/bd_28a4_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_11/bd_28a4_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_12/bd_28a4_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_16/bd_28a4_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_17/bd_28a4_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_18/bd_28a4_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_19/bd_28a4_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_20/bd_28a4_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_21/bd_28a4_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_22/bd_28a4_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_23/bd_28a4_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_24/bd_28a4_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/bd_0/ip/ip_25/bd_28a4_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_2_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_1/bd_e8f5_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_2/bd_e8f5_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_3/bd_e8f5_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_4/bd_e8f5_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_5/bd_e8f5_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_6/bd_e8f5_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_10/bd_e8f5_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_11/bd_e8f5_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_12/bd_e8f5_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_16/bd_e8f5_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_17/bd_e8f5_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_18/bd_e8f5_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_19/bd_e8f5_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_20/bd_e8f5_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_21/bd_e8f5_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_22/bd_e8f5_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_23/bd_e8f5_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_24/bd_e8f5_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/bd_0/ip/ip_25/bd_e8f5_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_axi_smc_3_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_xbar_0/platform_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/ip/platform_auto_pc_0/platform_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nevarez/work/vivado/sbs_fixedpoint/sbs_fixedpoint.srcs/sources_1/bd/platform/platform_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top platform_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef platform_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file platform_wrapper_utilization_synth.rpt -pb platform_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
