// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsbs_accelerator.h"

extern XSbs_accelerator_Config XSbs_accelerator_ConfigTable[];

XSbs_accelerator_Config *XSbs_accelerator_LookupConfig(u16 DeviceId) {
	XSbs_accelerator_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSBS_ACCELERATOR_NUM_INSTANCES; Index++) {
		if (XSbs_accelerator_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSbs_accelerator_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSbs_accelerator_Initialize(XSbs_accelerator *InstancePtr, u16 DeviceId) {
	XSbs_accelerator_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSbs_accelerator_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSbs_accelerator_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

