// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsbs_accelerator.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSbs_accelerator_CfgInitialize(XSbs_accelerator *InstancePtr, XSbs_accelerator_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSbs_accelerator_Start(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSbs_accelerator_IsDone(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSbs_accelerator_IsIdle(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSbs_accelerator_IsReady(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSbs_accelerator_EnableAutoRestart(XSbs_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSbs_accelerator_DisableAutoRestart(XSbs_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XSbs_accelerator_Set_layerSize(XSbs_accelerator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_LAYERSIZE_DATA, Data);
}

u32 XSbs_accelerator_Get_layerSize(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_LAYERSIZE_DATA);
    return Data;
}

void XSbs_accelerator_Set_kernelSize(XSbs_accelerator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_KERNELSIZE_DATA, Data);
}

u32 XSbs_accelerator_Get_kernelSize(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_KERNELSIZE_DATA);
    return Data;
}

void XSbs_accelerator_Set_vectorSize(XSbs_accelerator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_VECTORSIZE_DATA, Data);
}

u32 XSbs_accelerator_Get_vectorSize(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_VECTORSIZE_DATA);
    return Data;
}

void XSbs_accelerator_Set_epsilon(XSbs_accelerator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_EPSILON_DATA, Data);
}

u32 XSbs_accelerator_Get_epsilon(XSbs_accelerator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_EPSILON_DATA);
    return Data;
}

void XSbs_accelerator_InterruptGlobalEnable(XSbs_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_GIE, 1);
}

void XSbs_accelerator_InterruptGlobalDisable(XSbs_accelerator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_GIE, 0);
}

void XSbs_accelerator_InterruptEnable(XSbs_accelerator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_IER);
    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XSbs_accelerator_InterruptDisable(XSbs_accelerator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_IER);
    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XSbs_accelerator_InterruptClear(XSbs_accelerator *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSbs_accelerator_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XSbs_accelerator_InterruptGetEnabled(XSbs_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_IER);
}

u32 XSbs_accelerator_InterruptGetStatus(XSbs_accelerator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSbs_accelerator_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSBS_ACCELERATOR_CRTL_BUS_ADDR_ISR);
}

