// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "wide_div.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic wide_div::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic wide_div::ap_const_logic_0 = sc_dt::Log_0;
const bool wide_div::ap_const_boolean_1 = true;
const bool wide_div::ap_const_boolean_0 = false;

wide_div::wide_div(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1 = new sbs_fixedpoint_udiv_63ns_42ns_63_67_0<1,67,63,42,63>("sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1");
    sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1->clk(ap_clk);
    sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1->reset(ap_rst);
    sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1->din0(dividend_V_int_reg);
    sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1->din1(grp_fu_24_p1);
    sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1->ce(grp_fu_24_ce);
    sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1->dout(grp_fu_24_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state18_pp0_stage0_iter17);

    SC_METHOD(thread_ap_block_state19_pp0_stage0_iter18);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state20_pp0_stage0_iter19);

    SC_METHOD(thread_ap_block_state21_pp0_stage0_iter20);

    SC_METHOD(thread_ap_block_state22_pp0_stage0_iter21);

    SC_METHOD(thread_ap_block_state23_pp0_stage0_iter22);

    SC_METHOD(thread_ap_block_state24_pp0_stage0_iter23);

    SC_METHOD(thread_ap_block_state25_pp0_stage0_iter24);

    SC_METHOD(thread_ap_block_state26_pp0_stage0_iter25);

    SC_METHOD(thread_ap_block_state27_pp0_stage0_iter26);

    SC_METHOD(thread_ap_block_state28_pp0_stage0_iter27);

    SC_METHOD(thread_ap_block_state29_pp0_stage0_iter28);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state30_pp0_stage0_iter29);

    SC_METHOD(thread_ap_block_state31_pp0_stage0_iter30);

    SC_METHOD(thread_ap_block_state32_pp0_stage0_iter31);

    SC_METHOD(thread_ap_block_state33_pp0_stage0_iter32);

    SC_METHOD(thread_ap_block_state34_pp0_stage0_iter33);

    SC_METHOD(thread_ap_block_state35_pp0_stage0_iter34);

    SC_METHOD(thread_ap_block_state36_pp0_stage0_iter35);

    SC_METHOD(thread_ap_block_state37_pp0_stage0_iter36);

    SC_METHOD(thread_ap_block_state38_pp0_stage0_iter37);

    SC_METHOD(thread_ap_block_state39_pp0_stage0_iter38);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state40_pp0_stage0_iter39);

    SC_METHOD(thread_ap_block_state41_pp0_stage0_iter40);

    SC_METHOD(thread_ap_block_state42_pp0_stage0_iter41);

    SC_METHOD(thread_ap_block_state43_pp0_stage0_iter42);

    SC_METHOD(thread_ap_block_state44_pp0_stage0_iter43);

    SC_METHOD(thread_ap_block_state45_pp0_stage0_iter44);

    SC_METHOD(thread_ap_block_state46_pp0_stage0_iter45);

    SC_METHOD(thread_ap_block_state47_pp0_stage0_iter46);

    SC_METHOD(thread_ap_block_state48_pp0_stage0_iter47);

    SC_METHOD(thread_ap_block_state49_pp0_stage0_iter48);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state50_pp0_stage0_iter49);

    SC_METHOD(thread_ap_block_state51_pp0_stage0_iter50);

    SC_METHOD(thread_ap_block_state52_pp0_stage0_iter51);

    SC_METHOD(thread_ap_block_state53_pp0_stage0_iter52);

    SC_METHOD(thread_ap_block_state54_pp0_stage0_iter53);

    SC_METHOD(thread_ap_block_state55_pp0_stage0_iter54);

    SC_METHOD(thread_ap_block_state56_pp0_stage0_iter55);

    SC_METHOD(thread_ap_block_state57_pp0_stage0_iter56);

    SC_METHOD(thread_ap_block_state58_pp0_stage0_iter57);

    SC_METHOD(thread_ap_block_state59_pp0_stage0_iter58);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state60_pp0_stage0_iter59);

    SC_METHOD(thread_ap_block_state61_pp0_stage0_iter60);

    SC_METHOD(thread_ap_block_state62_pp0_stage0_iter61);

    SC_METHOD(thread_ap_block_state63_pp0_stage0_iter62);

    SC_METHOD(thread_ap_block_state64_pp0_stage0_iter63);

    SC_METHOD(thread_ap_block_state65_pp0_stage0_iter64);

    SC_METHOD(thread_ap_block_state66_pp0_stage0_iter65);

    SC_METHOD(thread_ap_block_state67_pp0_stage0_iter66);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8);

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_fu_24_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_int_reg );

    SC_METHOD(thread_grp_fu_24_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_24_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_fu_24_p10 );

    SC_METHOD(thread_grp_fu_24_p10);
    sensitive << ( divisor_V_int_reg );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "wide_div_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, dividend_V, "(port)dividend_V");
    sc_trace(mVcdFile, divisor_V, "(port)divisor_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7, "ap_block_state8_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8, "ap_block_state9_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9, "ap_block_state10_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10, "ap_block_state11_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter11, "ap_block_state12_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter12, "ap_block_state13_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter13, "ap_block_state14_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter14, "ap_block_state15_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter15, "ap_block_state16_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter16, "ap_block_state17_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage0_iter17, "ap_block_state18_pp0_stage0_iter17");
    sc_trace(mVcdFile, ap_block_state19_pp0_stage0_iter18, "ap_block_state19_pp0_stage0_iter18");
    sc_trace(mVcdFile, ap_block_state20_pp0_stage0_iter19, "ap_block_state20_pp0_stage0_iter19");
    sc_trace(mVcdFile, ap_block_state21_pp0_stage0_iter20, "ap_block_state21_pp0_stage0_iter20");
    sc_trace(mVcdFile, ap_block_state22_pp0_stage0_iter21, "ap_block_state22_pp0_stage0_iter21");
    sc_trace(mVcdFile, ap_block_state23_pp0_stage0_iter22, "ap_block_state23_pp0_stage0_iter22");
    sc_trace(mVcdFile, ap_block_state24_pp0_stage0_iter23, "ap_block_state24_pp0_stage0_iter23");
    sc_trace(mVcdFile, ap_block_state25_pp0_stage0_iter24, "ap_block_state25_pp0_stage0_iter24");
    sc_trace(mVcdFile, ap_block_state26_pp0_stage0_iter25, "ap_block_state26_pp0_stage0_iter25");
    sc_trace(mVcdFile, ap_block_state27_pp0_stage0_iter26, "ap_block_state27_pp0_stage0_iter26");
    sc_trace(mVcdFile, ap_block_state28_pp0_stage0_iter27, "ap_block_state28_pp0_stage0_iter27");
    sc_trace(mVcdFile, ap_block_state29_pp0_stage0_iter28, "ap_block_state29_pp0_stage0_iter28");
    sc_trace(mVcdFile, ap_block_state30_pp0_stage0_iter29, "ap_block_state30_pp0_stage0_iter29");
    sc_trace(mVcdFile, ap_block_state31_pp0_stage0_iter30, "ap_block_state31_pp0_stage0_iter30");
    sc_trace(mVcdFile, ap_block_state32_pp0_stage0_iter31, "ap_block_state32_pp0_stage0_iter31");
    sc_trace(mVcdFile, ap_block_state33_pp0_stage0_iter32, "ap_block_state33_pp0_stage0_iter32");
    sc_trace(mVcdFile, ap_block_state34_pp0_stage0_iter33, "ap_block_state34_pp0_stage0_iter33");
    sc_trace(mVcdFile, ap_block_state35_pp0_stage0_iter34, "ap_block_state35_pp0_stage0_iter34");
    sc_trace(mVcdFile, ap_block_state36_pp0_stage0_iter35, "ap_block_state36_pp0_stage0_iter35");
    sc_trace(mVcdFile, ap_block_state37_pp0_stage0_iter36, "ap_block_state37_pp0_stage0_iter36");
    sc_trace(mVcdFile, ap_block_state38_pp0_stage0_iter37, "ap_block_state38_pp0_stage0_iter37");
    sc_trace(mVcdFile, ap_block_state39_pp0_stage0_iter38, "ap_block_state39_pp0_stage0_iter38");
    sc_trace(mVcdFile, ap_block_state40_pp0_stage0_iter39, "ap_block_state40_pp0_stage0_iter39");
    sc_trace(mVcdFile, ap_block_state41_pp0_stage0_iter40, "ap_block_state41_pp0_stage0_iter40");
    sc_trace(mVcdFile, ap_block_state42_pp0_stage0_iter41, "ap_block_state42_pp0_stage0_iter41");
    sc_trace(mVcdFile, ap_block_state43_pp0_stage0_iter42, "ap_block_state43_pp0_stage0_iter42");
    sc_trace(mVcdFile, ap_block_state44_pp0_stage0_iter43, "ap_block_state44_pp0_stage0_iter43");
    sc_trace(mVcdFile, ap_block_state45_pp0_stage0_iter44, "ap_block_state45_pp0_stage0_iter44");
    sc_trace(mVcdFile, ap_block_state46_pp0_stage0_iter45, "ap_block_state46_pp0_stage0_iter45");
    sc_trace(mVcdFile, ap_block_state47_pp0_stage0_iter46, "ap_block_state47_pp0_stage0_iter46");
    sc_trace(mVcdFile, ap_block_state48_pp0_stage0_iter47, "ap_block_state48_pp0_stage0_iter47");
    sc_trace(mVcdFile, ap_block_state49_pp0_stage0_iter48, "ap_block_state49_pp0_stage0_iter48");
    sc_trace(mVcdFile, ap_block_state50_pp0_stage0_iter49, "ap_block_state50_pp0_stage0_iter49");
    sc_trace(mVcdFile, ap_block_state51_pp0_stage0_iter50, "ap_block_state51_pp0_stage0_iter50");
    sc_trace(mVcdFile, ap_block_state52_pp0_stage0_iter51, "ap_block_state52_pp0_stage0_iter51");
    sc_trace(mVcdFile, ap_block_state53_pp0_stage0_iter52, "ap_block_state53_pp0_stage0_iter52");
    sc_trace(mVcdFile, ap_block_state54_pp0_stage0_iter53, "ap_block_state54_pp0_stage0_iter53");
    sc_trace(mVcdFile, ap_block_state55_pp0_stage0_iter54, "ap_block_state55_pp0_stage0_iter54");
    sc_trace(mVcdFile, ap_block_state56_pp0_stage0_iter55, "ap_block_state56_pp0_stage0_iter55");
    sc_trace(mVcdFile, ap_block_state57_pp0_stage0_iter56, "ap_block_state57_pp0_stage0_iter56");
    sc_trace(mVcdFile, ap_block_state58_pp0_stage0_iter57, "ap_block_state58_pp0_stage0_iter57");
    sc_trace(mVcdFile, ap_block_state59_pp0_stage0_iter58, "ap_block_state59_pp0_stage0_iter58");
    sc_trace(mVcdFile, ap_block_state60_pp0_stage0_iter59, "ap_block_state60_pp0_stage0_iter59");
    sc_trace(mVcdFile, ap_block_state61_pp0_stage0_iter60, "ap_block_state61_pp0_stage0_iter60");
    sc_trace(mVcdFile, ap_block_state62_pp0_stage0_iter61, "ap_block_state62_pp0_stage0_iter61");
    sc_trace(mVcdFile, ap_block_state63_pp0_stage0_iter62, "ap_block_state63_pp0_stage0_iter62");
    sc_trace(mVcdFile, ap_block_state64_pp0_stage0_iter63, "ap_block_state64_pp0_stage0_iter63");
    sc_trace(mVcdFile, ap_block_state65_pp0_stage0_iter64, "ap_block_state65_pp0_stage0_iter64");
    sc_trace(mVcdFile, ap_block_state66_pp0_stage0_iter65, "ap_block_state66_pp0_stage0_iter65");
    sc_trace(mVcdFile, ap_block_state67_pp0_stage0_iter66, "ap_block_state67_pp0_stage0_iter66");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, grp_fu_24_p1, "grp_fu_24_p1");
    sc_trace(mVcdFile, grp_fu_24_p2, "grp_fu_24_p2");
    sc_trace(mVcdFile, grp_fu_24_ce, "grp_fu_24_ce");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, dividend_V_int_reg, "dividend_V_int_reg");
    sc_trace(mVcdFile, divisor_V_int_reg, "divisor_V_int_reg");
    sc_trace(mVcdFile, ap_return_int_reg, "ap_return_int_reg");
    sc_trace(mVcdFile, grp_fu_24_p10, "grp_fu_24_p10");
#endif

    }
}

wide_div::~wide_div() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sbs_fixedpoint_udiv_63ns_42ns_63_67_0_U1;
}

void wide_div::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_int_reg = grp_fu_24_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        dividend_V_int_reg = dividend_V.read();
        divisor_V_int_reg = divisor_V.read();
    }
}

void wide_div::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state10_pp0_stage0_iter9() {
    ap_block_state10_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state11_pp0_stage0_iter10() {
    ap_block_state11_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state12_pp0_stage0_iter11() {
    ap_block_state12_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state13_pp0_stage0_iter12() {
    ap_block_state13_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state14_pp0_stage0_iter13() {
    ap_block_state14_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state15_pp0_stage0_iter14() {
    ap_block_state15_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state16_pp0_stage0_iter15() {
    ap_block_state16_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state17_pp0_stage0_iter16() {
    ap_block_state17_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state18_pp0_stage0_iter17() {
    ap_block_state18_pp0_stage0_iter17 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state19_pp0_stage0_iter18() {
    ap_block_state19_pp0_stage0_iter18 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state20_pp0_stage0_iter19() {
    ap_block_state20_pp0_stage0_iter19 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state21_pp0_stage0_iter20() {
    ap_block_state21_pp0_stage0_iter20 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state22_pp0_stage0_iter21() {
    ap_block_state22_pp0_stage0_iter21 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state23_pp0_stage0_iter22() {
    ap_block_state23_pp0_stage0_iter22 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state24_pp0_stage0_iter23() {
    ap_block_state24_pp0_stage0_iter23 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state25_pp0_stage0_iter24() {
    ap_block_state25_pp0_stage0_iter24 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state26_pp0_stage0_iter25() {
    ap_block_state26_pp0_stage0_iter25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state27_pp0_stage0_iter26() {
    ap_block_state27_pp0_stage0_iter26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state28_pp0_stage0_iter27() {
    ap_block_state28_pp0_stage0_iter27 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state29_pp0_stage0_iter28() {
    ap_block_state29_pp0_stage0_iter28 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state30_pp0_stage0_iter29() {
    ap_block_state30_pp0_stage0_iter29 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state31_pp0_stage0_iter30() {
    ap_block_state31_pp0_stage0_iter30 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state32_pp0_stage0_iter31() {
    ap_block_state32_pp0_stage0_iter31 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state33_pp0_stage0_iter32() {
    ap_block_state33_pp0_stage0_iter32 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state34_pp0_stage0_iter33() {
    ap_block_state34_pp0_stage0_iter33 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state35_pp0_stage0_iter34() {
    ap_block_state35_pp0_stage0_iter34 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state36_pp0_stage0_iter35() {
    ap_block_state36_pp0_stage0_iter35 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state37_pp0_stage0_iter36() {
    ap_block_state37_pp0_stage0_iter36 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state38_pp0_stage0_iter37() {
    ap_block_state38_pp0_stage0_iter37 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state39_pp0_stage0_iter38() {
    ap_block_state39_pp0_stage0_iter38 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state40_pp0_stage0_iter39() {
    ap_block_state40_pp0_stage0_iter39 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state41_pp0_stage0_iter40() {
    ap_block_state41_pp0_stage0_iter40 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state42_pp0_stage0_iter41() {
    ap_block_state42_pp0_stage0_iter41 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state43_pp0_stage0_iter42() {
    ap_block_state43_pp0_stage0_iter42 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state44_pp0_stage0_iter43() {
    ap_block_state44_pp0_stage0_iter43 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state45_pp0_stage0_iter44() {
    ap_block_state45_pp0_stage0_iter44 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state46_pp0_stage0_iter45() {
    ap_block_state46_pp0_stage0_iter45 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state47_pp0_stage0_iter46() {
    ap_block_state47_pp0_stage0_iter46 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state48_pp0_stage0_iter47() {
    ap_block_state48_pp0_stage0_iter47 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state49_pp0_stage0_iter48() {
    ap_block_state49_pp0_stage0_iter48 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state50_pp0_stage0_iter49() {
    ap_block_state50_pp0_stage0_iter49 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state51_pp0_stage0_iter50() {
    ap_block_state51_pp0_stage0_iter50 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state52_pp0_stage0_iter51() {
    ap_block_state52_pp0_stage0_iter51 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state53_pp0_stage0_iter52() {
    ap_block_state53_pp0_stage0_iter52 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state54_pp0_stage0_iter53() {
    ap_block_state54_pp0_stage0_iter53 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state55_pp0_stage0_iter54() {
    ap_block_state55_pp0_stage0_iter54 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state56_pp0_stage0_iter55() {
    ap_block_state56_pp0_stage0_iter55 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state57_pp0_stage0_iter56() {
    ap_block_state57_pp0_stage0_iter56 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state58_pp0_stage0_iter57() {
    ap_block_state58_pp0_stage0_iter57 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state59_pp0_stage0_iter58() {
    ap_block_state59_pp0_stage0_iter58 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state60_pp0_stage0_iter59() {
    ap_block_state60_pp0_stage0_iter59 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state61_pp0_stage0_iter60() {
    ap_block_state61_pp0_stage0_iter60 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state62_pp0_stage0_iter61() {
    ap_block_state62_pp0_stage0_iter61 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state63_pp0_stage0_iter62() {
    ap_block_state63_pp0_stage0_iter62 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state64_pp0_stage0_iter63() {
    ap_block_state64_pp0_stage0_iter63 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state65_pp0_stage0_iter64() {
    ap_block_state65_pp0_stage0_iter64 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state66_pp0_stage0_iter65() {
    ap_block_state66_pp0_stage0_iter65 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state67_pp0_stage0_iter66() {
    ap_block_state67_pp0_stage0_iter66 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state8_pp0_stage0_iter7() {
    ap_block_state8_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_block_state9_pp0_stage0_iter8() {
    ap_block_state9_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void wide_div::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return = ap_return_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return = grp_fu_24_p2.read();
    }
}

void wide_div::thread_grp_fu_24_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_24_ce = ap_const_logic_1;
    } else {
        grp_fu_24_ce = ap_const_logic_0;
    }
}

void wide_div::thread_grp_fu_24_p1() {
    grp_fu_24_p1 =  (sc_lv<42>) (grp_fu_24_p10.read());
}

void wide_div::thread_grp_fu_24_p10() {
    grp_fu_24_p10 = esl_zext<63,42>(divisor_V_int_reg.read());
}

}

